### ISSUE TITLE
SSL Certificate Hostname Verification Issue with Graylog in Docker Environment

### ISSUE THREAD

**Issue by hsh-it** [Graylog2/docker-compose#51]
Hello Community,

I'm encountering an SSL certificate hostname verification issue in a Dockerized Graylog setup. The Graylog instance is unable to establish an SSL connection to the Elasticsearch/Opensearch node due to a hostname verification error.

Here's the error message from the Graylog logs:

```
ERROR: org.graylog2.storage.versionprobe.VersionProbe - Unable to retrieve version from Elasticsearch node: Hostname 074fbaa056fc not verified:
    certificate: sha256/zWp6JC/kWP9z/UUu/fGh3t2PxP6Nad7piMfWQI7Edi4=
    DN: CN=361fcc6804d7
    subjectAltNames: [0:0:0:0:0:0:0:1, 127.0.0.1, 172.19.0.2, localhost, 361fcc6804d7, 0:0:0:0:0:0:0:1].
```

It seems the container running Graylog (`074fbaa056fc`) is not included in the `subjectAltNames` of the certificate used by the Graylog datanode (`361fcc6804d7`), and hence the SSL handshake is failing.

The containers are assigned dynamic hostnames on each deployment, which makes it impractical to include them in the `subjectAltNames`. Here's a snippet of my `docker-compose.yml`:

```yaml
# ... (other configuration details)

services:
  graylog:
    image: graylog/graylog:5.2
    # ... (other configuration details)

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    # ... (other configuration details)

# ... (other configuration details)
```

Has anyone encountered a similar issue and found a way to configure SSL certificates correctly in such a dynamic environment? Any suggestions on how to include these dynamic hostnames in the certificate or a workaround to disable hostname verification securely would be greatly appreciated.
https://github.com/Graylog2/docker-compose/tree/main/open-core
Thank you in advance for your help!
